services:
  app:
    image: mozzo1000/crowdin-stats:latest
    environment:
      - MASTER_KEY=${MASTER_KEY}
      - DB_PATH=/data/db.sqlite
      - HOST=${HOST}
    volumes:
      - ./data:/data
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - app
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: unless-stopped

volumes:
  caddy_data:
